name: dia
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pytorch>=2.5
  - pytorch-cuda=12.1
  - torchvision
  - cmake
  - patchelf
  - swig
  - pip:
      - "stable-baselines3[extra]>=2.3"
      - gymnasium
      - shimmy
      - procgen2==0.10.7
      - hydra-core==1.3.2
      - rich
      - tensorboard
      - scikit-learn
      - opencv-python
      - ruff
      - black
      - isort
      - pytest
      - pytest-xdist
      - pytest-cov
