name: dia
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip>=23.3
  - numpy>=1.24
  - scipy>=1.10
  - matplotlib>=3.7
  - pytorch>=2.2
  - cpuonly
  - tensorboard>=2.12
  - networkx>=3.1
  - pip:
      # Gym classic API for our minimal envs; compatible with our code
      - gym==0.26.2
      - gym-notices>=0.0.8
      # ProcGen (CoinRun)
      - procgen>=0.10.7
      # Atari (Montezuma via ALE; use v5 IDs)
      - ale-py>=0.8.1
      - autorom[accept-rom-license]>=0.6.1
