name: dia-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip>=23.3
  - numpy>=1.24
  - scipy>=1.10
  - matplotlib>=3.7
  - pytorch>=2.2
  - pytorch-cuda=11.8
  - tensorboard>=2.12
  - networkx>=3.1
  - pip:
      - gym==0.26.2
      - gym-notices>=0.0.8
      - procgen>=0.10.7
      - ale-py>=0.8.1
      - autorom[accept-rom-license]>=0.6.1
