name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install deps
      run: |
        python -m pip install -U pip
        pip install -e . ruff black isort pytest
    - name: Lint
      run: |
        ruff check dia
        black --check dia
        isort --check-only dia
    - name: Tests
      run: pytest -q
